### ISSUE TITLE
Remove bcrypt-nodejs?

### ISSUE THREAD

**Issue by Spurux** [Spurux/project-n-server#4]
Is bcrypt-nodejs really necessary? Since there's only one password to check against, and that password is unassailable, is there really any reason to hash it?

**Comment by Spurux** [comment]
Pros:
- Fewer libaries

Cons:
- Seems a bit dangerous to have plain text password lying around

**Comment by Pankajtanwarbanna** [comment]
Yes. bcrypt-nodejs is really necessary. For any case your database may be leaked or it's data may be obtained by someone else. If such case happens then users' most sensitive data can be misused. Users have trusted you. Make use of one more library and be trust worthy :)

**Comment by Spurux** [comment]
@Pankajtanwarbanna, I'll heed your words, and let bcrypt stay. The encrypted string does after all give indirect access to the database. Thanks for the contribution. :-)
